<?php

/**
 * @file
 * take_control.module file, which produces the primary functionality.
 * Inspired by myself on being fed up to take control of Drupal files directory somehow.
 *
 */

/**
 * Implementation of hook_perm().
 */
function take_control_perm() {
  return array('administer take control', 'access take control');
}

///**
// * Implementation of hook_menu().
// */
//function take_control_menu() {
//  $items = array();
//
//  $items['admin/settings/take_control'] = array(
//      'title' => 'Take Control',
//      'description' => 'Administer Take Control, and add-on modules.',
//      'page callback' => 'drupal_get_form',
//      'page arguments' => array(
//          'take_control_settings_form',
//          NULL),
//      'access arguments' => array(
//          'administer take control'),
//      'file' => 'take_control.admin.inc');
//
//  $items['admin/settings/take_control/tc'] = array(
//      'title' => 'Take Control',
//      'description' => 'Take Control common settings.',
//      'weight' => -1,
//      'file' => 'take_control.admin.inc',
//      'type' => MENU_DEFAULT_LOCAL_TASK);
//
//  return $items;
//}
